### PR TITLE
Add examples to docs

### PR DESCRIPTION
**Pull request by bennn**
Two small examples

### CODE REVIEW

**Comment by rfindler** [comment]
This looks like it creates files during the docs build? Probably it shouldn't do that. One way to achieve that would be to enrich the contract-profile interface so that it doesn't have to create files (but then still use the same example expressions but actually use the new feature to put the content into a port somewhere and then extract it and fake the file->string call).

**Comment by bennn** [comment]
Yes, it makes files. I'll fix that.

**Comment by stamourv** [comment]
Yeah, I've never been super happy with the interface to the contract profiler.
Probably the cost breakdown (which is probably the most commonly-used view) could go on stdout, and the other views could be optional (and still go to files).

**Comment by rfindler** [comment]
How about a keyword argument that specifies a port? (Defaulting to
something that means "do the current behavior".)

**Comment by stamourv** [comment]
Maybe. That would also be a partial solution. We'd also need a switch to disable alternate views (which also create (different) files).

**Comment by stamourv** [comment]
Just pushed that change. Will merge the examples. Thanks!

**Comment by bennn** [comment]
Ah -- I took too long! I was going for a solution with parameters of type `(or/c path-string? output-port?)`, but nevermind.

**Comment by stamourv** [comment]
For the dot outputs, arbitrary ports don't really make sense because dot needs to process files.
For the cost breakdown, arbitrary ports could work. Feel free to make the change.

**Comment by rfindler** [comment]
I thought dot will take "-" on the command line to mean stdin? Or do I
misremember?

>

**Comment by stamourv** [comment]
Oh, I didn't know that. For the record, it's not controlled via a flag, but rather when no input files are specified.
In that case, we can avoid the intermediate dot files altogether. Or maybe only output them when no dot executable is found. I'll look into it.

**Pull request closed without merging**
